import type { EnvVarSpec } from "@/lib/types";

const ENV_PATH = ".env.local";
const ENV_EXAMPLE_PATH = ".env.example";

export function envLocalPath(): string {
  return ENV_PATH;
}

export function envExamplePath(): string {
  return ENV_EXAMPLE_PATH;
}

/** Normalize + validate env var specs from the agent tool. */
export function normalizeEnvVarSpecs(raw: unknown): EnvVarSpec[] {
  if (!Array.isArray(raw)) return [];
  const out: EnvVarSpec[] = [];
  const seen = new Set<string>();
  for (const item of raw) {
    if (!item || typeof item !== "object") continue;
    const row = item as Record<string, unknown>;
    const key = String(row.key || "")
      .trim()
      .replace(/[^\w]/g, "_")
      .toUpperCase();
    if (!key || seen.has(key)) continue;
    seen.add(key);
    out.push({
      key,
      label: String(row.label || key).trim() || key,
      description: String(row.description || "").trim() || undefined,
      howToGet: String(row.howToGet || row.how_to_get || "").trim() || undefined,
      placeholder: String(row.placeholder || "").trim() || undefined,
      required: row.required !== false,
      secret: row.secret !== false,
    });
  }
  return out;
}

/** Build a commented `.env.local` / `.env.example` from specs (empty values). */
export function buildEnvFileContent(
  vars: EnvVarSpec[],
  opts?: { title?: string; filled?: Record<string, string> },
): string {
  const title =
    opts?.title?.trim() ||
    "Generated by Luca AI — fill secrets in the chat Environment modal (or edit this file)";
  const lines: string[] = [`# ${title}`, `# Do not commit real secrets.`, ""];
  for (const v of vars) {
    if (v.description) lines.push(`# ${v.description}`);
    if (v.howToGet) lines.push(`# How to get: ${v.howToGet}`);
    const value = opts?.filled?.[v.key] ?? "";
    lines.push(`${v.key}=${value}`);
    lines.push("");
  }
  return lines.join("\n").trimEnd() + "\n";
}

/**
 * Merge KEY=value updates into an existing env file while keeping comments
 * and unknown keys.
 */
export function mergeEnvFileContent(
  existing: string,
  values: Record<string, string>,
): string {
  const lines = (existing || "").replace(/\r\n/g, "\n").split("\n");
  const remaining = { ...values };
  const out: string[] = [];

  for (const line of lines) {
    const m = line.match(/^([A-Za-z_][A-Za-z0-9_]*)\s*=(.*)$/);
    if (!m) {
      out.push(line);
      continue;
    }
    const key = m[1];
    if (Object.prototype.hasOwnProperty.call(remaining, key)) {
      out.push(`${key}=${remaining[key] ?? ""}`);
      delete remaining[key];
    } else {
      out.push(line);
    }
  }

  for (const [key, value] of Object.entries(remaining)) {
    if (!key.trim()) continue;
    if (out.length && out[out.length - 1] !== "") out.push("");
    out.push(`${key}=${value ?? ""}`);
  }

  return out.join("\n").replace(/\n+$/, "\n");
}

/** Parse KEY=value pairs from an env file (ignores comments). */
export function parseEnvFileContent(content: string): Record<string, string> {
  const out: Record<string, string> = {};
  for (const line of content.replace(/\r\n/g, "\n").split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq <= 0) continue;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    out[key] = value;
  }
  return out;
}

/** Heuristic: project already has DB/API backend wiring. */
export function projectLooksLikeBackend(
  files: Iterable<{ path: string; code?: string }>,
): boolean {
  for (const f of files) {
    if (/^app\/api\//i.test(f.path) && !/preview|upload|chats|images|generate-image/i.test(f.path)) {
      return true;
    }
    const code = f.code || "";
    if (
      /MONGODB_URI|DATABASE_URL|POSTGRES_|SUPABASE_|prisma\.|mongoose\.|drizzle|@supabase\/|mongodb\+|postgres:\/\//i.test(
        code,
      )
    ) {
      return true;
    }
    if (/lib\/(db|mongodb|prisma|supabase)\./i.test(f.path)) return true;
  }
  return false;
}
