import type { AgentStreamEvent } from "@/lib/agent/events";
import {
  ensurePhaseOnTimeline,
  inferFileAction,
  linesDelta,
  startNewPhase,
  summaryLinesFromText,
  upsertPhaseCommand,
  upsertPhaseFile,
} from "@/lib/agent/build-timeline";
import { assertInstallablePackage } from "@/lib/agent/packages";
import {
  ensureReactImport,
  ensureUseClientDirective,
  sanitizeGeneratedCode,
} from "@/lib/agent/sanitize-code";
import { storeSuiteStatus } from "@/lib/agent/store-suite";
import {
  isHostOwnedPreviewPath,
  normalizePreviewCss,
} from "@/lib/preview/normalize-css";
import type { BuildFileAction } from "@/lib/types";

function finalizeSourceCode(path: string, code: string): string {
  let next = sanitizeGeneratedCode(code);
  const isTsx = /\.(tsx|jsx)$/i.test(path);
  const isLayout = /(^|\/)layout\.tsx$/i.test(path);
  if (isTsx && !isLayout) {
    next = ensureUseClientDirective(next);
    next = ensureReactImport(next);
  }
  if (/\.css$/i.test(path)) {
    next = normalizePreviewCss(next);
  }
  return next;
}

function countButtonDeclarations(code: string): number {
  return (
    code.match(
      /\b(?:export\s+)?(?:const|function|class)\s+Button\b|\bButton\s*=\s*React\.forwardRef\b/g,
    ) || []
  ).length;
}

export type AgentAction = { name: string; description?: string };

export type AgentFile = {
  path: string;
  code: string;
  language?: string;
  query?: string;
  isImage?: boolean;
  aspect?: string;
  /** Live HTTPS image URL (Pexels) — never Gemini-generated bytes. */
  imageUrl?: string;
};

export type AgentState = {
  projectId: string;
  thinking: string[];
  files: Map<string, AgentFile>;
  /** Explicit npm deps (name → version) from install_package. */
  packages: Map<string, string>;
  deleted: string[];
  actions: AgentAction[];
  texts: string[];
  finished: boolean;
  /** Ordered chat timeline (phase / summary / status / thinking duration). */
  timeline: import("@/lib/types").AssistantPart[];
  /** Active phase id for grouping file/command events. */
  currentPhaseId: string;
  phaseSeq: number;
  /** Substrings that must appear in project files before finish() (clone mode). */
  cloneRequiredTokens: string[];
  /** Ecommerce ask — keep writing until the full suite exists (silent). */
  requireFullStore: boolean;
  /** Consecutive finish() rejects for store suite — break infinite loops. */
  storeFinishRejects: number;
  /** Consecutive edit_file misses — force write_file fallback. */
  editFailStreak: number;
  editFailPath: string;
};

export function createAgentState(projectId?: string | null): AgentState {
  return {
    projectId: projectId || "project",
    thinking: [],
    files: new Map(),
    packages: new Map(),
    deleted: [],
    actions: [],
    texts: [],
    finished: false,
    timeline: [],
    currentPhaseId: "",
    phaseSeq: 1,
    cloneRequiredTokens: [],
    requireFullStore: false,
    storeFinishRejects: 0,
    editFailStreak: 0,
    editFailPath: "",
  };
}

function normalizeNewlines(s: string): string {
  return s.replace(/\r\n/g, "\n").replace(/\r/g, "\n");
}

function phaseIdFromArgs(state: AgentState, args: Record<string, unknown>): string {
  const fromArg = String(args.phase_id || args.phaseId || "").trim();
  if (fromArg) {
    state.currentPhaseId = fromArg;
    return fromArg;
  }
  const { phaseId } = ensurePhaseOnTimeline(state, "Building project files");
  return phaseId;
}

export const AGENT_TOOL_DECLARATIONS = [
  {
    name: "phase",
    description:
      "REQUIRED before each batch of file/package work. One short plain sentence describing what you are about to build (e.g. \"Setting up the cart state and product data\"). No hype. Call this, then emit the write_file / install_package tools for that batch in the SAME step.",
    parameters: {
      type: "object",
      properties: {
        text: {
          type: "string",
          description: "One narrative sentence for the upcoming file/command batch",
        },
      },
      required: ["text"],
    },
  },
  {
    name: "think",
    description:
      "Internal planning only (not shown to the user). Include creative thesis, fonts, hex tokens, route map, packages. Client only sees \"Thought for Xs\".",
    parameters: {
      type: "object",
      properties: {
        text: {
          type: "string",
          description:
            "Feature map + CSS brand tokens + layout plan + packages — never shown in the UI",
        },
      },
      required: ["text"],
    },
  },
  {
    name: "set_project",
    description:
      "Set or keep the project id. Reuse the same id across edits unless starting a brand new project.",
    parameters: {
      type: "object",
      properties: {
        id: { type: "string", description: "Stable project id, kebab-case" },
      },
      required: ["id"],
    },
  },
  {
    name: "write_file",
    description:
      "Create a NEW file or fully rewrite a file. Call `phase` first for the batch. For small edits prefer edit_file.",
    parameters: {
      type: "object",
      properties: {
        path: {
          type: "string",
          description: 'File path like "app/page.tsx" or "components/hero.tsx"',
        },
        code: {
          type: "string",
          description: "Full file source code",
        },
        language: {
          type: "string",
          description: "Optional language hint: tsx, ts, css, js",
        },
        phase_id: {
          type: "string",
          description: "Optional phase id from the preceding phase tool",
        },
      },
      required: ["path", "code"],
    },
  },
  {
    name: "edit_file",
    description:
      "Surgically edit an existing project file by replacing an exact old_string with new_string. Prefer this for follow-up edits. Call `phase` first.",
    parameters: {
      type: "object",
      properties: {
        path: {
          type: "string",
          description: 'Existing file path like "app/page.tsx"',
        },
        old_string: {
          type: "string",
          description:
            "Exact text to find in the current file (copy from CURRENT PROJECT FILES)",
        },
        new_string: {
          type: "string",
          description: "Replacement text (only the changed portion)",
        },
        replace_all: {
          type: "boolean",
          description:
            "If true, replace every match. Default false (requires a unique old_string).",
        },
        phase_id: {
          type: "string",
          description: "Optional phase id from the preceding phase tool",
        },
      },
      required: ["path", "old_string", "new_string"],
    },
  },
  {
    name: "write_image",
    description:
      "Resolve a LIVE stock photo URL (Pexels) for a visual query. Does NOT generate AI images. Returns an https URL — put that URL in <img src> immediately (never local /images paths, never Gemini generation).",
    parameters: {
      type: "object",
      properties: {
        path: {
          type: "string",
          description:
            'Logical path key e.g. "public/images/hero.jpg" (rewritten to the live URL in code)',
        },
        query: {
          type: "string",
          description:
            "Short search query for Pexels (e.g. \"artisan coffee cup steam dark wood\")",
        },
        aspect: {
          type: "string",
          description: "Optional aspect like 16:9, 1:1, 9:16",
        },
      },
      required: ["path", "query"],
    },
  },
  {
    name: "delete_file",
    description: "Delete a file from the current project. Call `phase` first.",
    parameters: {
      type: "object",
      properties: {
        path: { type: "string" },
        phase_id: { type: "string" },
      },
      required: ["path"],
    },
  },
  {
    name: "install_package",
    description:
      "Install an npm dependency into the preview runtime. Call `phase` first, then batch all installs together. Do NOT install next/react/react-dom.",
    parameters: {
      type: "object",
      properties: {
        name: {
          type: "string",
          description: 'Package name, e.g. "sonner" or "@radix-ui/react-toast"',
        },
        version: {
          type: "string",
          description:
            "Optional semver (e.g. 1.7.1). Omit to use a pinned/compatible version.",
        },
        phase_id: { type: "string" },
      },
      required: ["name"],
    },
  },
  {
    name: "message_user",
    description:
      "Chat/Q&A only — short plain reply. For builds: use `phase` during work and `finish.summary` at the end. Never per-file narration.",
    parameters: {
      type: "object",
      properties: {
        text: { type: "string" },
      },
      required: ["text"],
    },
  },
  {
    name: "suggest_actions",
    description:
      "Suggest 6-7 follow-up actions after finishing the main task. Advanced next steps only. For stores/boutiques NEVER suggest: shop page, PDP, cart, checkout, search, filters, size guide, admin CRUD, profile, or live images — those must already ship on turn 1. Suggest Stripe/auth/DB/email/analytics instead.",
    parameters: {
      type: "object",
      properties: {
        actions: {
          type: "array",
          description: "Prefer 6–7 short action names",
          items: {
            type: "object",
            properties: {
              name: { type: "string" },
              description: { type: "string" },
            },
            required: ["name"],
          },
        },
      },
      required: ["actions"],
    },
  },
  {
    name: "finish",
    description:
      "End the turn after shipping the full ask. summary = plain one-line-per-feature-area bullets (no marketing adjectives like stunning/award-caliber).",
    parameters: {
      type: "object",
      properties: {
        summary: {
          type: "string",
          description:
            "Plain lines of what got built (one feature area per line). No hype.",
        },
      },
    },
  },
] as const;

export type ToolName = (typeof AGENT_TOOL_DECLARATIONS)[number]["name"];

export async function executeAgentTool(
  state: AgentState,
  name: string,
  args: Record<string, unknown>,
): Promise<{ ok: boolean; result: string; events: AgentStreamEvent[] }> {
  switch (name) {
    case "phase": {
      const text = String(args.text || "").trim();
      if (!text) return { ok: false, result: "phase.text required", events: [] };
      const phaseId = startNewPhase(state, text);
      return {
        ok: true,
        result: `phase=${phaseId}`,
        events: [{ type: "phase", id: phaseId, text }],
      };
    }
    case "think": {
      const text = String(args.text || "").trim();
      if (!text) return { ok: false, result: "think.text required", events: [] };
      state.thinking.push(text);
      const words = text.split(/\s+/).length;
      const durationSec = Math.max(1, Math.min(12, Math.round(words / 40)));
      // Client gets duration only — never raw reasoning text
      state.timeline.push({ type: "thinking", text: "", durationSec });
      return {
        ok: true,
        result: "recorded",
        events: [
          { type: "thinking", text: "", durationSec },
          { type: "thinking_done", durationSec },
        ],
      };
    }
    case "set_project": {
      const id = String(args.id || "")
        .trim()
        .replace(/\s+/g, "-");
      if (!id) return { ok: false, result: "set_project.id required", events: [] };
      state.projectId = id;
      return {
        ok: true,
        result: `project=${id}`,
        events: [{ type: "project", id }],
      };
    }
    case "write_file": {
      const path = String(args.path || "")
        .trim()
        .replace(/^\/+/, "");
      if (!path) return { ok: false, result: "write_file.path required", events: [] };
      if (isHostOwnedPreviewPath(path)) {
        return {
          ok: false,
          result: `Do not write "${path}" — host-owned (Tailwind v4 uses @import "tailwindcss" in CSS + postcss.config; no tailwind.config). Put brand tokens in app/globals.css or app/brand.css instead.`,
          events: [],
        };
      }
      const code = finalizeSourceCode(path, String(args.code ?? ""));
      if (!code.trim()) {
        return { ok: false, result: "write_file.code required", events: [] };
      }
      if (
        /components\/ui\/button\.tsx$/i.test(path) &&
        countButtonDeclarations(code) > 1
      ) {
        return {
          ok: false,
          result:
            'components/ui/button.tsx defines Button more than once — causes "Button is defined multiple times". Write a single Button (one forwardRef/const). Prefer editing the existing scaffold; do not paste two Button components into one file.',
          events: [],
        };
      }
      const language =
        String(args.language || "").trim() ||
        (path.endsWith(".css")
          ? "css"
          : path.endsWith(".ts")
            ? "ts"
            : path.endsWith(".js")
              ? "js"
              : "tsx");
      const existed = state.files.has(path);
      const before = state.files.get(path)?.code;
      const action: BuildFileAction = inferFileAction(existed);
      const delta = linesDelta(before, code);
      const phaseId = phaseIdFromArgs(state, args);
      state.files.set(path, { path, code, language });
      state.deleted = state.deleted.filter((p) => p !== path);
      if (state.editFailPath === path || state.editFailStreak > 0) {
        state.editFailStreak = 0;
        state.editFailPath = "";
      }
      upsertPhaseFile(state, {
        path,
        action,
        status: "done",
        language,
        linesDelta: delta,
      });
      return {
        ok: true,
        result: `wrote ${path} (${code.length} chars)`,
        events: [
          {
            type: "file",
            path,
            action,
            status: "done",
            phaseId,
            language,
            code,
            linesDelta: delta,
          },
        ],
      };
    }
    case "edit_file": {
      const path = String(args.path || "")
        .trim()
        .replace(/^\/+/, "");
      const oldStringRaw = String(args.old_string ?? "");
      const newString = sanitizeGeneratedCode(String(args.new_string ?? ""));
      const replaceAll = Boolean(args.replace_all);
      if (!path) {
        return { ok: false, result: "edit_file.path required", events: [] };
      }
      if (isHostOwnedPreviewPath(path)) {
        return {
          ok: false,
          result: `Do not edit "${path}" — host-owned preview tooling. Style via app/globals.css with @import "tailwindcss" + CSS variables.`,
          events: [],
        };
      }
      if (!oldStringRaw) {
        return {
          ok: false,
          result: "edit_file.old_string required (exact text from the current file)",
          events: [],
        };
      }

      // Break infinite old_string-not-found loops — force full rewrite
      if (
        state.editFailPath === path &&
        state.editFailStreak >= 2
      ) {
        const existingBlocked = state.files.get(path);
        return {
          ok: false,
          result: [
            `STOP. edit_file has failed ${state.editFailStreak} times on "${path}".`,
            `Do NOT call edit_file again for this path.`,
            `Call write_file with path="${path}" and the COMPLETE updated file contents.`,
            existingBlocked?.code
              ? `Current file (${existingBlocked.code.length} chars) — rewrite from this:\n\`\`\`\n${existingBlocked.code.slice(0, 2500)}\n\`\`\``
              : "",
          ]
            .filter(Boolean)
            .join("\n"),
          events: [],
        };
      }

      const existing = state.files.get(path);
      if (!existing || existing.isImage) {
        return {
          ok: false,
          result: `edit_file: "${path}" is not loaded. Use write_file with the full file contents.`,
          events: [],
        };
      }

      const code = normalizeNewlines(existing.code);
      const oldString = normalizeNewlines(oldStringRaw);
      const matches = code.split(oldString).length - 1;
      if (matches === 0) {
        if (state.editFailPath === path) {
          state.editFailStreak += 1;
        } else {
          state.editFailPath = path;
          state.editFailStreak = 1;
        }

        const head = code.slice(0, 1800);
        if (state.editFailStreak >= 2) {
          return {
            ok: false,
            result: [
              `edit_file old_string not found again on "${path}".`,
              `STOP retrying edit_file. Call write_file now with the FULL updated file.`,
              `Current file starts with:\n\`\`\`\n${head}\n\`\`\``,
            ].join("\n"),
            events: [],
          };
        }
        return {
          ok: false,
          result: [
            `edit_file: old_string not found in "${path}".`,
            `Retry ONCE with an exact shorter unique snippet, or prefer write_file for the whole file.`,
            `File head:\n\`\`\`\n${head}\n\`\`\``,
          ].join("\n"),
          events: [],
        };
      }
      if (matches > 1 && !replaceAll) {
        return {
          ok: false,
          result: `edit_file: old_string matched ${matches} times. Make old_string more unique, or set replace_all=true.`,
          events: [],
        };
      }
      const nextCode = finalizeSourceCode(
        path,
        replaceAll
          ? code.split(oldString).join(newString)
          : code.replace(oldString, newString),
      );
      const language = existing.language || "tsx";
      const delta = linesDelta(existing.code, nextCode);
      const phaseId = phaseIdFromArgs(state, args);
      state.files.set(path, { ...existing, code: nextCode, language });
      state.deleted = state.deleted.filter((p) => p !== path);
      state.editFailStreak = 0;
      state.editFailPath = "";
      upsertPhaseFile(state, {
        path,
        action: "update",
        status: "done",
        language,
        linesDelta: delta,
      });
      return {
        ok: true,
        result: `edited ${path} (${matches} replacement${matches === 1 ? "" : "s"})`,
        events: [
          {
            type: "file",
            path,
            action: "update",
            status: "done",
            phaseId,
            language,
            code: nextCode,
            linesDelta: delta,
          },
        ],
      };
    }
    case "write_image": {
      const path = String(args.path || "")
        .trim()
        .replace(/^\/+/, "");
      const query = String(args.query || "").trim();
      if (!path || !query) {
        return {
          ok: false,
          result: "write_image.path and query required",
          events: [],
        };
      }
      const aspect = args.aspect ? String(args.aspect) : undefined;

      const { fetchPexelsPhoto } = await import("@/lib/pexels-image");
      const photo = await fetchPexelsPhoto(query, aspect);
      if (!photo?.url) {
        return {
          ok: false,
          result:
            "No Pexels photo found for that query. Try a shorter/clearer query, or paste a live https image URL directly into <img src>.",
          events: [],
        };
      }
      const url = photo.url;
      const publicPath = path.startsWith("public/")
        ? `/${path.slice("public/".length)}`
        : path.startsWith("/")
          ? path
          : `/${path}`;

      state.files.set(path, {
        path,
        code: url,
        language: "txt",
        query,
        isImage: true,
        aspect,
        imageUrl: url,
      });

      // Rewrite any already-written files that still point at the local path
      const events: AgentStreamEvent[] = [
        { type: "image", path, query, aspect, url },
      ];
      const variants = [
        publicPath,
        path,
        path.replace(/^public\//, "/"),
        `/${path.replace(/^public\//, "")}`,
      ];
      const phaseId = phaseIdFromArgs(state, args);
      for (const [filePath, file] of state.files) {
        if (file.isImage || !file.code) continue;
        let code = file.code;
        let changed = false;
        for (const v of variants) {
          if (code.includes(`"${v}"`) || code.includes(`'${v}'`)) {
            code = code.split(`"${v}"`).join(`"${url}"`);
            code = code.split(`'${v}'`).join(`'${url}'`);
            changed = true;
          }
        }
        if (changed) {
          state.files.set(filePath, { ...file, code });
          const delta = linesDelta(file.code, code);
          upsertPhaseFile(state, {
            path: filePath,
            action: "update",
            status: "done",
            language: file.language,
            linesDelta: delta,
          });
          events.push({
            type: "file",
            path: filePath,
            action: "update",
            status: "done",
            phaseId,
            language: file.language,
            code,
            linesDelta: delta,
          });
        }
      }

      return {
        ok: true,
        result: [
          `LIVE_IMAGE_URL=${url}`,
          `Use this exact https URL in <img src="..."> (and CSS backgrounds).`,
          `Do NOT use ${publicPath} or generate AI images.`,
          `Photographer: ${photo.photographer}`,
        ].join(" "),
        events,
      };
    }
    case "delete_file": {
      const path = String(args.path || "")
        .trim()
        .replace(/^\/+/, "");
      if (!path) {
        return { ok: false, result: "delete_file.path required", events: [] };
      }
      const before = state.files.get(path)?.code;
      const phaseId = phaseIdFromArgs(state, args);
      state.files.delete(path);
      if (!state.deleted.includes(path)) state.deleted.push(path);
      const delta = before ? -linesDelta(undefined, before) : 0;
      upsertPhaseFile(state, {
        path,
        action: "delete",
        status: "done",
        linesDelta: delta,
      });
      return {
        ok: true,
        result: `deleted ${path}`,
        events: [
          { type: "delete", path },
          {
            type: "file",
            path,
            action: "delete",
            status: "done",
            phaseId,
            linesDelta: delta,
          },
        ],
      };
    }
    case "install_package": {
      const checked = assertInstallablePackage(
        String(args.name || ""),
        args.version != null ? String(args.version) : null,
      );
      if (!checked.ok) {
        return { ok: false, result: checked.error, events: [] };
      }
      const { name: pkgName, version } = checked;
      const phaseId = phaseIdFromArgs(state, args);
      state.packages.set(pkgName, version);
      const detail = `${pkgName}@${version}`;
      upsertPhaseCommand(state, {
        name: `npm i ${pkgName}`,
        status: "done",
        detail,
      });
      return {
        ok: true,
        result: `install ${pkgName}@${version} — import it in code next`,
        events: [
          { type: "package", name: pkgName, version },
          {
            type: "command",
            name: `npm i ${pkgName}`,
            status: "done",
            phaseId,
            detail,
          },
        ],
      };
    }
    case "message_user": {
      const text = String(args.text || "").trim();
      if (!text) {
        return { ok: false, result: "message_user.text required", events: [] };
      }
      // Block premature "store is ready" delivery while suite files are still unwritten
      if (state.requireFullStore && state.files.size > 0) {
        const suite = storeSuiteStatus(state.files);
        const claimsDone =
          /\b(is ready|fully (functional|complete)|what's included|i('ve| have) created|award-caliber)\b/i.test(
            text,
          );
        if (!suite.ok && claimsDone) {
          return {
            ok: false,
            result: [
              "Do not deliver yet. Keep calling write_file / write_image for:",
              ...suite.writeNext.map((p) => `- ${p}`),
              "Short progress lines only until those exist. Do not tell the user the store is ready.",
            ].join("\n"),
            events: [],
          };
        }
      }
      // Builds use phase + finish.summary; message_user is for Q&A / short chat
      state.texts.push(text);
      state.timeline.push({ type: "text", text });
      return {
        ok: true,
        result: "ok",
        events: [{ type: "text", text }],
      };
    }
    case "suggest_actions": {
      const raw = Array.isArray(args.actions) ? args.actions : [];
      const actions = raw
        .map((a) => {
          const item = a as { name?: string; description?: string };
          return {
            name: String(item.name || "").trim(),
            description: item.description
              ? String(item.description)
              : undefined,
          };
        })
        .filter((a) => a.name);
      if (state.requireFullStore && state.files.size > 0) {
        const suite = storeSuiteStatus(state.files);
        if (!suite.ok) {
          return {
            ok: false,
            result: [
              "Write these files first, then suggest_actions (Stripe/auth/CMS only):",
              ...suite.writeNext.map((p) => `- ${p}`),
            ].join("\n"),
            events: [],
          };
        }
      }
      const next = actions.slice(0, 7);
      const count = next.length;
      if (count < 6) {
        return {
          ok: false,
          result: `Need 6–7 follow-up actions (got ${count}). Call suggest_actions again with more advanced next steps — not unfinished first-turn work (e.g. for stores avoid suggesting Cart/PDP/Search).`,
          events: [],
        };
      }
      state.actions = next;
      return {
        ok: true,
        result: `${count} actions`,
        events: [{ type: "actions", actions: state.actions }],
      };
    }
    case "finish": {
      if (state.cloneRequiredTokens.length) {
        const blob = [...state.files.values()]
          .map((f) => f.code)
          .join("\n");
        const missing = state.cloneRequiredTokens.filter(
          (t) => t && !blob.includes(t),
        );
        const page = state.files.get("app/page.tsx");
        const pageTooThin = !page || page.code.length < 2800;
        if (missing.length || pageTooThin) {
          const reasons = [
            missing.length
              ? `still missing scraped asset URLs in code: ${missing.join(", ")}`
              : "",
            pageTooThin
              ? "app/page.tsx is too short — scroll the screenshot and build every section to the footer"
              : "",
          ]
            .filter(Boolean)
            .join("; ");
          return {
            ok: false,
            result: `Cannot finish yet — ${reasons}. Keep matching the screenshot, then finish again.`,
            events: [],
          };
        }
      }
      if (state.requireFullStore && state.files.size > 0) {
        const suite = storeSuiteStatus(state.files);
        if (!suite.ok) {
          state.storeFinishRejects += 1;
          // Escape hatch: after repeated rejects, stop burning keys — allow finish
          if (state.storeFinishRejects >= 4) {
            console.warn(
              `[agent] store finish escape after ${state.storeFinishRejects} rejects — allowing finish`,
            );
          } else {
            return {
              ok: false,
              result: [
                "Write these missing route files with write_file (full file, not tiny edit_file):",
                ...suite.writeNext.map((p) => `- ${p}`),
                "Then call finish. Do not message the user about this.",
              ].join("\n"),
              events: [],
            };
          }
        } else {
          state.storeFinishRejects = 0;
        }
      }
      const summary = String(args.summary || "").trim();
      const events: AgentStreamEvent[] = [];
      if (summary) {
        const lines = summaryLinesFromText(summary);
        if (lines.length) {
          state.texts.push(lines.join("\n"));
          state.timeline.push({ type: "summary", lines });
          events.push({ type: "summary", lines });
        }
      }
      state.finished = true;
      return {
        ok: true,
        result: "finished",
        events,
      };
    }
    default:
      return { ok: false, result: `Unknown tool: ${name}`, events: [] };
  }
}
